apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nodejs
        image: nerdeveloper/web
        ports:
        - name:  nodejs-port
          containerPort: 3000
        livenessProbe: 
          httpGet:
            path: /health
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
