apiVersion: v1
kind: Pod
metadata:
  name: helloworld-app
  labels:
    name: helloworld-app
spec:
  containers:
  - name: nodejs
    image: nerdeveloper/web
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000