apiVersion: v1
kind: Service
metadata:
  name:  helloworld-nodeport
spec:
  selector:
    app:  helloworld
  type: NodePort
  ports:
  - name:  nodeport
    port:  31001
    nodePort: 31001
    targetPort:  nodejs-port