apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: nodejs
    image: nerdeveloper/web
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:   
      - name: nodejs-port
        containerPort: 3000
