#Use the following YAMLs to create a cStor Storage Pool.
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  maxPools: 3
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
      - blockdevice-031e9e80329c72bc48dee3d2733a08fe
      - blockdevice-10af5d691c90c27be0c79d90a9e4aa34
      - blockdevice-27e489767ba03f1d4896188d50754082
---